version: '3'

services:
  webserver:
    container_name: webserver
    hostname: webserver_bo_dev
    build:
      dockerfile: docker/prod/Dockerfile-proxy
      context: .
    ports:
      - 8800:80
    networks:
      - app
    depends_on:
      - api

  api:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: .
    container_name: api
    expose:
      - 9000
    volumes:
      - ./:/src
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - '5432:5432'
    volumes:
      - ./psdata:/var/lib/postgresql/data
    networks:
      - app

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app

networks:
  app:
    driver: bridge
